config/routes.rb
Rails.application.routes.draw do
  
  get 'relationships/create'
  get 'relationships/destroy'

  resources :posts do
    patch :vote_add, on: :member
    patch :vote_reduce, on: :member
    resources :comments, controller: 'comment' do
      get '/accept/:status_id', to: 'comment#accept', as: 'accept'
    end
  end
  devise_for :users

  resources :relationships, only: [:create, :destroy]

  get '/homepage',  to: 'welcome#index', as: 'welcome'
  get '/dashboard/', to: 'dashboard#index', as: 'dashboard'
  get '/users/:id', to: 'welcome#user_page', as: 'welcome_user_page'
  get 'user_detail/:id', to: 'users#show', as: 'user_detail'
  get '/feed', to: 'users#feed', as: 'user_feed'
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :accepted, -> { where(status: 1) }

  scope :user_comments, ->(user_id) { where(user_id: user_id).where(status: 0)}
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  scope :availables, -> { where(visible: true).order(created_at: :desc) }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followed, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  validates :username, presence: true, length: { minimum: 5, maximum: 50 }
  validates :email, presence: true

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy, inverse_of: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy, inverse_of: :followed

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    following << other_user unless self == other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    Post.where("user_id IN (?)", following_ids).availables
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
   end
end
  

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user!
  before_action :is_post_user, only: %i[accept]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    CommentWaitingJob.set(wait: 2.days).perform_later(@comment.id)
    @user_comment = @post.comments.where(user_id: current_user).where(status: 0)
    respond_to do |format|
      format.html { redirect_to @post }
      format.js  { @user_comment }
    end
  end

  def accept
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:comment_id])
    if comment.post.user.eql?(current_user)
      if comment.locked
        flash[:warn] = 'Processing time is over.'
      else
        comment.update!(status: params[:status_id])
        flash[:notice] = 'Process successfully.'
      end
    else
      flash[:warn] = 'Unauthorized process.'
    end
    redirect_to dashboard_path
  end

  private

  def is_post_user
    post = Post.find(params[:post_id])
    unless post.user == current_user
      respond_to do |format|
        format.html { redirect_to root_path, notice: "You don't permission to page" }
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:title, :content).merge(user: current_user)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @posts = current_user.posts.all
    @comments = []
    @posts.each do |post|
      comments_arr = post.comments
      comments_arr.each { |comment| @comments << comment }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy vote_add vote_reduce ]
  before_action :authenticate_user!
  before_action :check_user, only: %i[edit update destroy]

  def show
    @comments = @post.comments.accepted
    @user_comment = @post.comments.where(user_id: current_user).where(status: 0)
  end

  def new
    @post = current_user.posts.new
  end

  def edit
  end

  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def vote_add
    @post.update(vote_count: @post.vote_count + 1)
    respond_to do |format|
      format.js
    end
  end

  def vote_reduce
    @post.update(vote_count: @post.vote_count - 1)
    respond_to do |format|
      format.js
    end
  end

  private

  def check_user
    unless @post.user == current_user
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: "You shall not pass." }
      end
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :visible)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
      @user = User.find(params[:followed_id])
      current_user.follow(@user)
  
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
    end
  
    def destroy
      @user = Relationship.find(params[:id]).followed
      current_user.unfollow(@user)
  
      respond_to do |format|
        format.html { redirect_to @user }
        format.js
      end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
  
    def show
      @user = User.find(params[:id])
      @comments = Comment.where(user_id: @user).where(status: 1)
    end
  
    def feed
      @posts = current_user.feed
      @users = User.all.order(created_at: :desc)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_feed_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def substr(description)
      truncate(description, :length => 100)
    end
  
    def comment_status_text(comment_status)
      if comment_status == 0
        'No process'
      elsif comment_status == 1
        'Accepted'
      else
        'Declined'
      end
    end
  end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/create.js.erb
$(document).ready(function () {
    $('#input_title').val('');
    $('#textarea_content').val('');
    var user_comment_value = ""+
        "<% if @user_comment.any? %>"+
          "<% @user_comment.each do |comment| %>"+
            "<div class=\"card mb-5\">" +
              "<div class=\"card-heading text-center p-3 border\">" +
                "<b><%= comment.title %></b>" +
                "<span class=\"badge badge-pill badge-success float-right\">Waiting for Accept</span>" +
              "</div>"+
              "<div class=\"card-body\">" +
              "<%= comment.content %>"+
              "</div>"+
              "<div class=\"card-footer\">"+
                "<div class=\"row text-center\">"+
                  "<div class=\"col-sm-6\">✍ <%= comment.user.username %><br></div>"+
                  "<div class=\"col-sm-6\">⏱️ <%= time_ago_in_words(comment.created_at) %></div>"+
                "</div>"+
              "</div>"+
            "</div>"+
          "<% end %>"+
        "<% end %>";

    $('#user_comment').html(user_comment_value);
});

app/views/comment/show.html.erb
<h1><%= @comment.title %></h1>
<p><%= @comment.content %></p>
<p><%if @comment.accept %>Onaylanmış<% else %> Onaylanmamış <% end %></p>


<%= link_to 'Change visible status', post_comment_accept_path(@comment.post, @comment.id), method: :patch %>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col-sm-10">
    <h1>Posts</h1>
  </div>
  <div class="col-sm-2">
    <%= link_to 'New Post', new_post_path, class: 'btn btn-primary float-right' %>
  </div>
</div>


<% if @posts.any? %>
  <table class="table">
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= substr(post.content) %></td>
        <td><%= post.visible %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning text-center">
    You don't have a post.
  </div>
<% end %>
<br>


<div class="row">
  <div class="col-sm-12">
    <h1>Comments</h1>
  </div>
</div>

<% if @comments.any? %>
  <table class="table">
    <thead>
    <th>Post title</th>
    <th>Title</th>
    <th>Content</th>
    <th>Created Date</th>
    <th>Visible</th>
    <th class="text-center">Comment Process</th>
    </thead>

    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post.title %></td>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= time_ago_in_words(comment.created_at) %></td>
        <td><%= comment_status_text(comment.status) %></td>
        <td class="text-center">
          <% if comment.locked %>
            Locked
          <% else %>
            <% if comment.status == 0 %>
              <%= link_to '✔', post_comment_accept_path(comment.post, comment.id, 1) %> |
              <%= link_to '❌', post_comment_accept_path(comment.post, comment.id, 2) %>
            <% elsif comment.status == 1 %>
              <%= link_to '❌', post_comment_accept_path(comment.post, comment.id, 2) %>
            <% else %>
              <%= link_to '✔', post_comment_accept_path(comment.post, comment.id, 1) %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-warning text-center">
    No Comment
  </div>
<% end %>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kadir_Atali</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    a:hover{
        text-decoration: none;
    }
  </style>
</head>

<body>

<nav class="navbar navbar-expand-sm bg-white navbar-white">
  <div class="container">

    <%= link_to 'Kadir Atalı Blog', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">

      <ul class="navbar-nav ml-auto">
        <% unless user_signed_in? %>

          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Hi <strong><%= current_user.username %></strong></a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Dashboard', dashboard_path, class: 'dropdown-item' %>
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item'%>
              <%= link_to "Logout", destroy_user_session_path, :method=> :delete, class: 'dropdown-item' %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container" style="margin-top: 20px;">

  <% unless notice.nil? %>
    <div class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= notice %>
    </div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-warning alert-dismissible">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= alert %>
    </div>
  <% end %>
  <%= yield %>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div class="alert alert-warning" id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= form.label :title%>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group field">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control" %>
  </div>

  <div class="form-group form-check field">
    <%= form.check_box :visible, class: "form-check-input" %>
    <%= form.label :visible %>
  </div>

  <div class="form-group actions">
    <%= form.submit :class => 'form-control btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_user_comment.erb
<div class="card mb-5">
  <div class="card-heading text-center p-3 border">
    <b><%= user_comments.title %></b>
    <span class="badge badge-pill badge-success float-right">Waiting for Accept</span>
  </div>
  <div class="card-body">
    <%= user_comments.content %>
  </div>
  <div class="card-footer">
    <div class="row text-center">
      <div class="col-sm-6">
        ✍ <%= user_comments.user.username %><br>
      </div>
      <div class="col-sm-6">
        ⏱️ <%= time_ago_in_words(user_comments.created_at) %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>
<%= link_to 'Show', @post %> |
<%= link_to 'Back', dashboard_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<% if @posts.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.visible %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  You don't have a post.
<% end %>
<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>
<%= link_to 'Back', posts_path, class: 'btn btn-warning' %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-12">
    <p>
    <h1>
      <%= @post.title %>
    </h1>
    </p>
    <p>
      ✍ <%= link_to @post.user.username, user_detail_path(@post.user) %> | ⏱️<%= time_ago_in_words(@post.created_at) %>
    </p>

    <p>
      <%= @post.content %>
    </p>

    <br>
    <p> Vote(<strong id="vote_count"><%= @post.vote_count %></strong>)
      <br>
      <% if user_signed_in? && @user != current_user %>
          <%= link_to '👍', vote_add_post_path(@post), method: :patch, class: 'btn btn-primary', remote: true %>
        | <%= link_to '👎', vote_reduce_post_path(@post), method: :patch, class: 'btn btn-primary', remote: true %>
      <% end %>
    </p>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <h2>Comments</h2>
    <hr>
    <div id="user_comment">
      <% if @user_comment.any? %>
        <% @user_comment.each do |comment| %>
          <div class="card mb-5">
            <div class="card-heading text-center p-3 border">
              <b><%= comment.title %></b>
              <span class="badge badge-pill badge-success float-right">Waiting for Accept</span>
            </div>
            <div class="card-body">
              <%= comment.content %>
            </div>
            <div class="card-footer">
              <div class="row text-center">
                <div class="col-sm-6">
                  ✍ <%= comment.user.username %><br>
                </div>
                <div class="col-sm-6">
                  ⏱️ <%= time_ago_in_words(comment.created_at) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <br>
    <% if @comments.any? %>
      <% @comments.each do |comment| %>
        <div class="card mb-5">
          <div class="card-heading text-center p-3 border">
            <b><%= comment.title %></b>
          </div>
          <div class="card-body">
            <%= comment.content %>
          </div>
          <div class="card-footer">
            <div class="row text-center">
              <div class="col-sm-6">
                ✍ <%= comment.user.username %><br>
              </div>
              <div class="col-sm-6">
                ⏱️ <%= time_ago_in_words(comment.created_at) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning">There is no comment</div>
    <% end %>

  </div>
</div>

<br>

<div class="row">
  <div class="col-12">
    <h2>Add a comment</h2>

    <div id="comment_form">
      <%= form_with(model: [@post, @post.comments.build], local: false) do |form| %>
        <p>
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control', id: 'input_title' %>
        </p>
        <p>
          <%= form.label :content %>
          <%= form.text_area :content, class: 'form-control', id: 'textarea_content' %>
        </p>

        <p>
          <%= form.submit :class => 'form-control btn btn-primary' %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<br>

<% if current_user == @post.user_id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', _back_url %>

app/views/posts/vote_add.js.erb
$(document).ready(function () {
    $('#vote_count').html("<%= @post.vote_count %>");
});

app/views/posts/vote_reduce.js.erb
$(document).ready(function () {
    $('#vote_count').html("<%= @post.vote_count %>");
});

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, local: false) do |f| %>
  <%= hidden_field_tag :followed_id, @user.id %>
  <%= f.submit 'Follow', class: 'btn btn-primary' %>
<% end %>

app/views/users/_follow_form.html.erb
<div id='follow_form'>
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
              html: { method: :delete }, local: false) do |f| %>
  <%= f.submit 'Unfollow', class: 'btn btn-primary' %>
<% end %>

app/views/users/feed.html.erb
<h1>Kadir_Atali</h1>
<div class="row">
  <div class="col-sm-8">
    <% if @posts.any? %>
      <% for post in @posts %>
        <div class="jumbotron" style="padding: 10px;">
          <h2><%= link_to post.title, post_path(post.id) %></h2>
          <p>✍ <%= link_to post.user.username, user_detail_path(post.user) %> |
            ⏱️<%= time_ago_in_words(post.created_at) %> ago | 📝 <%= post.comments.accepted.count %> </p>
          <p><%= substr(post.content) %></p>
          <p>Vote: <%= post.vote_count %></p>
        </div>
      <% end %>
    <% else %>
      <div class="alert alert-warning">
        No post here. Can you add a post please ?
      </div>
    <% end %>
  </div>
  <div style="text-align:center;height:100px;width:50%;background-color:#FFE4C4;margin:20px;border:2px solid;border-radius:10px">
    <% if @users.count <= 1 %>
      <h3 style="padding-top:20px">You are online</h3>
    <% else %>
      <h3>New Users</h3>
      <% for user in @users %>
        <p>
          <%= link_to user.username, user_detail_path(user) %> -
          <%= user.posts.count %> posts
        </p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-1">
    <div style="border-radius: 80px;height: 80px; width: 80px;background-color: #666666;"></div>
  </div>
  <div class="col-sm-6">
    <strong>Username:</strong> <%= @user.username %>
    <br>
    <strong>Email:</strong> <%= @user.email %>
    <br>
    <strong>Registered Date:</strong> <%= time_ago_in_words(@user.created_at) %> ago
    <br>
  </div>
  <div class="col-sm-5 mb-5">
    <div id="followers">
      <strong>Follower: </strong> <%= @user.following.count %> <br>
      <strong>Following: </strong> <%= @user.followers.count %>
    </div>
    <% if user_signed_in? && @user != current_user %>
      <p><%= render 'follow_form' %></p>
    <% end %>
  </div>
  <div class="col-sm-12">
    <h2><%= @user.username %>'s posts</h2>
  </div>
  <div class="col-sm-12">
    <% if @user.posts.availables.any? %>
      <table class="table">
        <thead>
        <th>Title</th>
        <th>Content</th>
        <th>Comment</th>
        <th>Created Date</th>
        </thead>
        <tbody>
        <% for post in @user.posts.availables %>
          <tr>
            <td><%= link_to post.title, post_path(post.id) %></td>
            <td><%= substr(post.content) %></td>
            <td><%= post.comments.count %></td>
            <td><%= time_ago_in_words(post.created_at) %> ago</td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-warning">
        <%= @user.username %>'s haven't post.
      </div>
    <% end %>
  </div>
  <div class="col-sm-12">
    <h2><%= @user.username %>'s comments</h2>
  </div>
  <div class="col-sm-12">
    <% if @comments.any? %>
      <table class="table">
        <thead>
        <th>Post Title</th>
        <th>Title</th>
        <th>Content</th>
        <th>Created Date</th>
        </thead>
        <tbody>
        <% for comment in @comments %>
          <tr>
            <td><%= link_to comment.post.title, post_path(comment.post.id) %></td>
            <td><%= comment.title %></td>
            <td><%= substr(comment.content) %></td>
            <td><%= time_ago_in_words(comment.created_at) %> ago</td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <div class="alert alert-warning">
        <%= @user.username %>'s haven't comment.
      </div>
    <% end %>
  </div>
  <br>
  <%= link_to 'back', _back_url, class: 'btn btn-primary' %>
</div>

app/views/welcome/index.html.erb
<h1>Kadir_Atali Blog</h1>


<p style="font-weight:bold;font-family:sans-serif">Welcome to my blog,please sign up.&#128512</p>



<br>

app/views/welcome/user_page.html.erb
<strong>Username:</strong> <%= @user.username %>
<br>
<strong>Email:</strong> <%= @user.email %>
<br>
<% if @user.posts.any? %>
  <table>
    <thead>
    <tr>

      <th>Title</th>
      <% if user_signed_in? %>
        <th>Created By</th>
        <th>Created Date</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% for post in @user.posts %>
      <tr>
        <% if user_signed_in? %>
          <td><%= link_to post.title, post_path(post.id) %></td>
          <td><%= link_to post.user.username, welcome_user_page_path(post.user.id) %></td>
          <td><%= post.created_at %></td>
        <% else %>
          <td><%= post.title %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  no post here.
<% end %>

<br>
<%= link_to 'back', _back_url %>