blogapp/config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, controller: 'comment' do
      patch '/accept', to: 'comment#accept', as: 'accept'
    end
  end
  devise_for :users

  get '/users/:id', to: 'welcome#user_page', as: 'welcome_user_page'
  get '/dashboard/', to: 'dashboard#index', as: 'dashboard'
  root 'welcome#index'
end

blogapp/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  scope :accepteds, -> { where(accept: true) }
end

blogapp/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  validates :title, presence: true
  validates :content, presence: true

  scope :availables, -> { where(visible: true) }
end

blogapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
  validates :username, presence: true, length: { minimum: 5, maximum: 50 }
  validates :email, presence: true

end

blogapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |user|
   user.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.permit(:account_update) { |user|
   user.permit(:username, :email, :password, :password_confirmation, :current_password) }
    end
  end
  

blogapp/app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :authenticate_user!
  before_action :is_post_user

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.update!(user: current_user)
    redirect_to @post
  end

  def show
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def accept
    post = Post.find(params[:post_id])
    comment = post.comments.find(params[:comment_id])
    if comment.accept
      comment.update!(accept: false)
    else
      comment.update!(accept: true)
    end
    flash[:notice] = 'Process successfully.'
    redirect_to root_path
  end

  private

  def is_post_user
    unless Post.find(params[:post_id]).user == current_user
      respond_to do |format|
        format.html { redirect_to root_path, notice: "You don't permission to page" }
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:title, :content)
  end
end

blogapp/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index show edit update destroy]
  before_action :check_user, only: %i[edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = current_user.posts.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @comments = @post.comments.accepteds
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def check_user
    unless @post.user == current_user
      respond_to do |format|
        format.html { redirect_to dashboard_path, notice: "You are not login." }
      end
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :content, :visible)
  end
end

blogapp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.availables
  end

  def user_page
    @user = User.find(params[:id])
  end
end

blogapp/app/helpers/application_helper.rb
module ApplicationHelper
end

blogapp/app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<% if @posts.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.visible %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  You don't have a post.
<% end %>
<br>

<h1>Comments</h1>

<% if @comments.any? %>
  <table>
    <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Visible</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= comment.accept %></td>
        <td><%= link_to 'Accept', post_comment_path(comment.post, comment.id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  No Accepted Comment
<% end %>

<br>
<%= link_to 'New Post', new_post_path %>

blogapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MediumClone</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<p>
  <%= link_to 'Homepage', root_path %>
  <% if user_signed_in? %>
    | <%= link_to 'User Dashboard', dashboard_path %>
  <% end %>
</p>

<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>
  <%= link_to 'Edit profile', edit_user_registration_path %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<%= yield %>
</body>
</html>

blogapp/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

blogapp/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

blogapp/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

blogapp/app/views/posts/show.html.erb
<p>
<h1>

  <%= @post.title %>
</h1>
</p>
<p>
<h3>
  <%= @post.content %>
</h3>
</p>
<p>
  <%= @post.user.username %>  |   <%= @post.created_at %>
</p>

<br>

<h2>Comments</h2>

<% if @comments.any? %>
  <% @comments.each do |comment| %>
    <p><%= comment.title %></p>
    <p><%= comment.content %></p>
    <hr>
  <% end %>
<% else %>
  <p>There is no comment</p>
<% end %>
<h2>Add a comment</h2>

<%= form_with model: [@post, @post.comments.build] do |form| %>
  <p>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :content %>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<br>

<% if current_user == @post.user_id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>

blogapp/app/views/welcome/index.html.erb
<h1>Kadir_Atali Blog</h1>

<% if @posts.any? %>
  <table>
    <thead>
    <tr>

      <th>Title</th>
      <% if user_signed_in? %>
        <th>Created By</th>
        <th>Created Date</th>
      <% end %>
    </tr>
    </thead>
    <tbody>
    <% for post in @posts %>
      <tr>
        <% if user_signed_in? %>
          <td><%= link_to post.title, post_path(post.id) %></td>
          <td><%= link_to post.user.username, welcome_user_page_path(post.user.id) %></td>
          <td><%= post.created_at %></td>
        <% else %>
          <td><%= post.title %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  no post here.
<% end %>